field: a83f7a9b-98c4-42aa-84d2-20f467930ae5 # Svsw Heading
fieldLayouts:
  c3b2da7b-07ad-4372-8810-9a43ace34f58:
    tabs:
      -
        elements:
          -
            fieldUid: 960e97c4-20da-4598-bfdd-b399cd3a945c # Heading First
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8b8f4580-9ac1-456e-ae6e-d8f016b573c3 # Description First
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8b8f4580-9ac1-456e-ae6e-d8f016b573c3: # Description First
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: descriptionFirst
    instructions: ''
    name: 'Description First'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  960e97c4-20da-4598-bfdd-b399cd3a945c: # Heading First
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headingFirst
    instructions: ''
    name: 'Heading First'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: addsection
name: 'Add Section'
sortOrder: 1
