field: f6cf9783-aa13-4640-a921-7e17d9026a02 # Svsw Description
fieldLayouts:
  b65ec632-6bf0-47c7-957e-8b69b053108c:
    tabs:
      -
        elements:
          -
            fieldUid: 1bc69689-1b2b-41dc-b9fd-33b232cb8973 # Heading Second
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ea1f2cf7-719f-4876-8b91-17fd7a62a050 # Description Second
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1bc69689-1b2b-41dc-b9fd-33b232cb8973: # Heading Second
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headingSecond
    instructions: ''
    name: 'Heading Second'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ea1f2cf7-719f-4876-8b91-17fd7a62a050: # Description Second
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: descriptionSecond
    instructions: ''
    name: 'Description Second'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: addSection
name: 'Add Section'
sortOrder: 1
