field: 245ed696-7d35-4ad3-9260-1f5efda67301 # Slider Image
fieldLayouts:
  01ceb275-5226-4445-ada5-1e27f6d4559d:
    tabs:
      -
        elements:
          -
            fieldUid: 82aff86c-3487-4ca9-b40b-7015ad6e1f07 # Upload
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  82aff86c-3487-4ca9-b40b-7015ad6e1f07: # Upload
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: upload
    instructions: ''
    name: Upload
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:f93ad09d-00b5-43c5-b494-8c628ac9803b' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Upload Slider Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:f93ad09d-00b5-43c5-b494-8c628ac9803b' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:f93ad09d-00b5-43c5-b494-8c628ac9803b' # Uploads
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: slider
name: Slider
sortOrder: 1
