field: 043d676b-e6cf-4463-95f7-5f63f9e30076 # Veggies
fieldLayouts:
  71dcec34-59bf-4eba-9b39-dd10cb6000f9:
    tabs:
      -
        elements:
          -
            fieldUid: 6b8e7b95-aace-4048-aa19-d86f2a69f6e2 # Veggie Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8c0f9cab-ba1c-4dab-9069-578496c23958 # Veggie Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9acf7969-ba3b-4c99-af02-c91120eb6ae8 # Veggie Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6b8e7b95-aace-4048-aa19-d86f2a69f6e2: # Veggie Name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: veggieName
    instructions: ''
    name: 'Veggie Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8c0f9cab-ba1c-4dab-9069-578496c23958: # Veggie Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: veggieDescription
    instructions: ''
    name: 'Veggie Description'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  9acf7969-ba3b-4c99-af02-c91120eb6ae8: # Veggie Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: veggieImage
    instructions: ''
    name: 'Veggie Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:f93ad09d-00b5-43c5-b494-8c628ac9803b' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Upload a vaggie images'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:f93ad09d-00b5-43c5-b494-8c628ac9803b' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:f93ad09d-00b5-43c5-b494-8c628ac9803b' # Uploads
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: veggie
name: Veggie
sortOrder: 1
