columnSuffix: null
contentColumnType: string
fieldGroup: b86df002-6bb7-4247-aecc-f08c733ccd3e # veggie Section
handle: veggies
instructions: ''
name: Veggies
searchable: false
settings:
  contentTable: '{{%matrixcontent_veggies}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
