defaultPlacement: end
enableVersioning: true
handle: home
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a17e147f-e160-4544-9496-8246b3d7d5cc: # Quiz-app
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
